name: Generate snake animation

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:
  push:
    branches:
      - master

concurrency:
  group: snake-animation-${{ github.ref }}
  cancel-in-progress: true
jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg?palette=github-dark

      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@df5cc2bfa78282ded844b354faee141f06b41865
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
